name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run unit tests with Vitest
      run: npx vitest run --coverage

    - name: Start development server
      run: |
        nohup npm run dev &

    - name: Wait for server to be ready
      run: npx wait-on http://localhost:3000

    - name: Run Cypress tests
      run: npx cypress run --browser chrome